{{- if not .Values.garnet.existingSecret }}
{{- if .Values.garnet.config }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "garnet.fullname" . }}-config
  labels:
    {{- include "garnet.labels" . | nindent 4 }}
type: Opaque
data:
  garnet.conf: {{ .Values.garnet.config | b64enc | quote }}
{{- end }}
{{- end }}